### ISSUE TITLE
Add notice on supported NodeJS version

### ISSUE THREAD

**Issue by micalevisk** [Protowalker/algebraify#1]
Hi! Since you're using `util/types`

https://github.com/Protowalker/algebraify/blob/29e2e13bd2e8616baf3b43bfe2b07c471141b4b2/src/InferredGenerator.ts#L1

would be cool to have this in your `package.json`:

```json
  "engineStrict": true,
  "engines": {
    "node": ">=16",
  },
```

right? Or maybe you can change that line to `import { types } from "util";` and use `types.isPromise` or something like that

---

Looks like in node14 there's no `"util/types"` module, only `"util"`

![image](https://user-images.githubusercontent.com/13461315/142803196-978353c3-7871-4aa8-ab71-dbfa34c16253.png)

**Comment by Protowalker** [comment]
Shoot, thanks for pointing that out! It was a complete brainfart that I used that at all -- at some point I changed `foo instanceof Promise` to `isPromise(foo)` just to see if there was a difference, and then forgot to change it back. I removed it and bumped the patch version, 0.2.2 has the fix.

Thanks again!
